export const state = {
  categories: [
    {
      id: "cat1",
      name: "Main Dish",
      image: "/media/categoryIconDefault.svg",
      items: [
        {
          id: "item1",
          categoryId: "cat1",
          name: "Grilled Ribeye Steak",
          price: 28,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item2",
          categoryId: "cat1",
          name: "Roasted Chicken with Herbs",
          price: 19,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item3",
          categoryId: "cat1",
          name: "Pan-Seared Salmon",
          price: 24,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item4",
          categoryId: "cat1",
          name: "Beef Stroganoff",
          price: 21,
          image: "/media/categoryIconDefault.svg",
        },
      ],
    },
    {
      id: "cat2",
      name: "Fast Food",
      image: "/media/categoryIconDefault.svg",
      items: [
        {
          id: "item1",
          categoryId: "cat2",
          name: "French Fries",
          price: 5,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item2",
          categoryId: "cat2",
          name: "Hot Dog",
          price: 7,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item3",
          categoryId: "cat2",
          name: "Chicken Nuggets",
          price: 8,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item4",
          categoryId: "cat2",
          name: "Onion Rings",
          price: 6,
          image: "/media/categoryIconDefault.svg",
        },
      ],
    },
    {
      id: "cat3",
      name: "Burgers",
      image: "/media/categoryIconDefault.svg",
      items: [
        {
          id: "item1",
          categoryId: "cat3",
          name: "Classic Cheeseburger",
          price: 11,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item2",
          categoryId: "cat3",
          name: "Bacon BBQ Burger",
          price: 13,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item3",
          categoryId: "cat3",
          name: "Mushroom Swiss Burger",
          price: 12,
          image: "/media/categoryIconDefault.svg",
        },
        {
          id: "item4",
          categoryId: "cat3",
          name: "Double Beef Burger",
          price: 15,
          image: "/media/categoryIconDefault.svg",
        },
      ],
    },
  ],
  currentUserID: null,
  selectedCategoryID: null,
  selectedItemID: null,
  isEditMode: false,
  editingCategoryID: null,
  editingItemID: null,
};
